name: Analyses Snapshot Test

on:
  workflow_dispatch:
    inputs:
      ANALYSIS_REF:
        description: 'Branch or tag that provides the analysis output at test runtime'
        required: true
        default: 'edge'
      SNAPSHOT_REF:
        description: 'Branch or tag that provides the snapshot and test code at test runtime'
        required: true
        default: 'edge'
  schedule:
    - cron:  '26 7 * * *' # 7:26 AM UTC

jobs:
  build-and-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      ANALYSIS_REF: ${{ github.event.inputs.ANALYSIS_REF || 'edge' }}
      SNAPSHOT_REF: ${{ github.event.inputs.SNAPSHOT_REF || 'edge' }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ env.SNAPSHOT_REF }}

    - name: Docker Build
      working-directory: app-testing
      run: make build-opentrons-analysis

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pipenv'
        cache-dependency-path: app-testing/Pipfile.lock

    - name: Setup Python Dependencies
      working-directory: app-testing
      run: make setup

    - name: Run Test
      id: run_test
      working-directory: app-testing
      run: make snapshot-test

    - name: Upload Report
      if: '!cancelled()'
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: app-testing/results/
